### ISSUE TITLE
APK? 

### ISSUE THREAD

**Issue by tamielbr** [aburgostejada/Telecam#1]
hi I was wondering if the APK is available for download and if this project is current. thanks!

**Comment by aburgostejada** [comment]
Hi, currently the app is not in development anymore, mostly because of android wear remote camera feature. But I can get you the apk, I will upload it, later.  Thanks for asking.

**Comment by aburgostejada** [comment]
uploaded it.

**Comment by tamielbr** [comment]
Thanks!
